# Generated by Django 4.2.3 on 2023-07-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_course_alter_news_options_lesson_courseteachers'),
    ]

    operations = [
    ]
