# Generated by Django 4.2.3 on 2023-07-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_course_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseteachers',
            options={'verbose_name': 'учитель', 'verbose_name_plural': 'учителя'},
        ),
    ]
